<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<?php echo '/css/scorers.css'; ?>">
</head>
<body>
<?php if ($flash) : ?>
<p style="color:chartreuse"><?= $flash['success'][0] ?></p>
<?php endif; ?>

<div style="text-align:center">
<a href="/users2?page=<?= $page + 1 ?>">вперед</a>&nbsp;&nbsp;&nbsp;
<a href="/users2?page=<?= $page - 1 ?>">назад</a>
</div>

<h1>Top England Goal Scorers</h1>

<form style="padding-left:200px" action="<?= $post_form_example ?>">
    <input type="submit" value="Add User">
</form>
<div align="right" style="padding-right:200px; margin-bottom:8px">
  <label>You logged in as <b><?= $username ?></b></label>
<form action="/" method="post">
    <input type="hidden" name="logout" value="true">
    <input type="submit" value="Logout">
</form>
</div>
<table id="racetimes">
    <tr id="firstrow">
      <th>Player</th>
      <th>Goals</th>
      <th>First</th>
      <th>Latest</th>
      <th>Latest</th>
   </tr>
   <?php foreach ($scorers as $scorer) : ?>
    <tr>
      <td><?= $scorer['email'] ?></td>
      <td><?= $scorer['nickname'] ?></td>
      <td><a href="/users2/<?= $scorer['id'] ?>">DETAILED INFO...</a></td>
      <td><a href="/users2/<?= $scorer['id'] ?>/edit">EDIT INFO...</a></td>
      <td><form action="/users2/<?= $scorer['id'] ?>" method="post">
              <input type="hidden" name="_METHOD" value="DELETE">
              <input type="submit" value="Remove">
          </form></td>
    </tr>
   <?php endforeach; ?>
</table>
